export const LEVELS = [
  {
    id: 1,
    title: 'Moving Button',
    subtitle: 'The button has a personal agenda.',
    type: 'moving-button',
    prompt: 'Click the button before it runs away.',
    accent: 'from-fuchsia-500 to-cyan-400',
  },
  {
    id: 2,
    title: 'Shrinking Button',
    subtitle: 'The UI is trying to become a dot.',
    type: 'shrinking-button',
    prompt: 'Click the tiny button before it vanishes.',
    accent: 'from-amber-400 to-orange-500',
  },
  {
    id: 3,
    title: 'Fake Loading Screen',
    subtitle: 'It is loading absolutely nothing.',
    type: 'fake-loading',
    prompt: 'Wait for the fake progress bar to finish.',
    accent: 'from-emerald-400 to-teal-500',
  },
  {
    id: 4,
    title: 'Infinite Loading at 99%',
    subtitle: 'The computer believes in destiny.',
    type: 'loading-99',
    prompt: 'Watch the bar become spiritually stuck.',
    accent: 'from-violet-500 to-indigo-500',
  },
  {
    id: 5,
    title: 'Fake Virus Popup',
    subtitle: 'Your machine is definitely infected by vibes.',
    type: 'fake-virus',
    prompt: 'Dismiss the popup and continue.',
    accent: 'from-rose-500 to-pink-500',
  },
  {
    id: 6,
    title: 'Fake Windows Update',
    subtitle: 'This update has no end state.',
    type: 'windows-update',
    prompt: 'Pretend the update is important.',
    accent: 'from-sky-500 to-blue-500',
  },
  {
    id: 7,
    title: 'Mouse Following Button',
    subtitle: 'The button is following your cursor like a pet.',
    type: 'mouse-follow',
    prompt: 'Try to touch the button anyway.',
    accent: 'from-lime-400 to-emerald-500',
  },
  {
    id: 8,
    title: 'Reverse Controls',
    subtitle: 'The game is secretly inverted.',
    type: 'reverse-controls',
    prompt: 'Use the wrong direction on purpose.',
    accent: 'from-cyan-400 to-blue-600',
  },
  {
    id: 9,
    title: 'Button Duplication',
    subtitle: 'Every solution spawns a new problem.',
    type: 'duplicate-button',
    prompt: 'Choose the single button that is not a duplicate.',
    accent: 'from-purple-500 to-fuchsia-500',
  },
  {
    id: 10,
    title: 'One Correct Button',
    subtitle: 'The real answer is hiding in a sea of nonsense.',
    type: 'find-correct',
    prompt: 'Find the only button that makes sense.',
    accent: 'from-yellow-400 to-amber-500',
  },
  {
    id: 11,
    title: 'Fake CAPTCHA',
    subtitle: 'A bot would not survive this.',
    type: 'captcha',
    prompt: 'Prove you are not a robot by touching the checkbox.',
    accent: 'from-red-500 to-orange-500',
  },
  {
    id: 12,
    title: 'Simon Says',
    subtitle: 'The instructions are mostly suggestions.',
    type: 'simon-says',
    prompt: 'Follow the glowing command.',
    accent: 'from-indigo-500 to-violet-500',
  },
  {
    id: 13,
    title: 'Memory Puzzle',
    subtitle: 'Only the most recent memory matters.',
    type: 'memory-puzzle',
    prompt: 'Tap the card that remembers the last prank.',
    accent: 'from-cyan-400 to-emerald-400',
  },
  {
    id: 14,
    title: 'Screen Rotate',
    subtitle: 'The world turned sideways.',
    type: 'rotate-screen',
    prompt: 'Accept the new orientation.',
    accent: 'from-pink-500 to-rose-500',
  },
  {
    id: 15,
    title: 'Upside Down UI',
    subtitle: 'It is impossible to judge anything correctly.',
    type: 'upside-down',
    prompt: 'Flip the room and continue.',
    accent: 'from-teal-400 to-cyan-500',
  },
  {
    id: 16,
    title: 'Gravity Mode',
    subtitle: 'Everything fell into the wrong direction.',
    type: 'gravity',
    prompt: 'Let the buttons fall into place.',
    accent: 'from-blue-500 to-slate-600',
  },
  {
    id: 17,
    title: 'Dark Mode Activated',
    subtitle: 'The game has become a haunted terminal.',
    type: 'dark-mode',
    prompt: 'Embrace the darkness.',
    accent: 'from-slate-800 to-slate-950',
  },
  {
    id: 18,
    title: 'Lights Flicker',
    subtitle: 'The room keeps pretending to blink.',
    type: 'lights-flicker',
    prompt: 'Click through the flicker.',
    accent: 'from-white to-slate-300',
  },
  {
    id: 19,
    title: 'Random Notifications',
    subtitle: 'The system pesters you with nonsense.',
    type: 'fake-notifications',
    prompt: 'Dismiss the nonsense bundle.',
    accent: 'from-orange-500 to-amber-400',
  },
  {
    id: 20,
    title: 'Fake Discord Message',
    subtitle: 'A suspiciously urgent ping appears.',
    type: 'discord-message',
    prompt: 'Reply to the fake notification.',
    accent: 'from-indigo-400 to-purple-500',
  },
  {
    id: 21,
    title: 'Error Dialogs',
    subtitle: 'The game is now a collection of popups.',
    type: 'error-dialog',
    prompt: 'Close the error windows.',
    accent: 'from-red-600 to-rose-500',
  },
  {
    id: 22,
    title: 'DVD Logo',
    subtitle: 'The logo refuses to stay still.',
    type: 'dvd-logo',
    prompt: 'Catch the bouncing logo.',
    accent: 'from-fuchsia-500 to-lime-400',
  },
  {
    id: 23,
    title: 'Emoji Rain',
    subtitle: 'The sky is now a meme storm.',
    type: 'emoji-rain',
    prompt: 'Let the emojis fall and proceed.',
    accent: 'from-rose-400 to-yellow-400',
  },
  {
    id: 24,
    title: 'Screen Shake',
    subtitle: 'Your screen has become unstable.',
    type: 'screen-shake',
    prompt: 'Survive the shake and continue.',
    accent: 'from-pink-500 to-cyan-400',
  },
  {
    id: 25,
    title: 'Fake Browser Crash',
    subtitle: 'The browser is having a temper tantrum.',
    type: 'browser-crash',
    prompt: 'Recover from the fake crash.',
    accent: 'from-slate-500 to-fuchsia-500',
  },
  {
    id: 26,
    title: 'Blue Screen of Death',
    subtitle: 'The system has become a meme.',
    type: 'bsod',
    prompt: 'Press restart and keep going.',
    accent: 'from-blue-600 to-sky-400',
  },
  {
    id: 27,
    title: 'Restart Countdown',
    subtitle: 'The device is preparing for a dramatic reboot.',
    type: 'restart-countdown',
    prompt: 'Watch the countdown and pretend to panic.',
    accent: 'from-amber-500 to-orange-500',
  },
  {
    id: 28,
    title: 'Rickroll',
    subtitle: 'The prank has become a song.',
    type: 'rickroll',
    prompt: 'Click the button before the tune gets stuck.',
    accent: 'from-green-500 to-emerald-500',
  },
  {
    id: 29,
    title: 'Impossible Math',
    subtitle: 'The arithmetic has become a philosophy problem.',
    type: 'impossible-math',
    prompt: 'Solve the impossible question.',
    accent: 'from-violet-500 to-lime-500',
  },
  {
    id: 30,
    title: 'Fake Ending',
    subtitle: 'The game is finally over, obviously.',
    type: 'fake-ending',
    prompt: 'Claim the victory and think about your choices.',
    accent: 'from-rose-500 to-amber-400',
  },
  {
    id: 31,
    title: 'Secret Final Ending',
    subtitle: 'The joke was always deeper than expected.',
    type: 'secret-final-ending',
    prompt: 'Enter the hidden ending and accept your fate.',
    accent: 'from-slate-900 to-cyan-500',
  },
];

export const getLevelById = (id) => LEVELS.find((level) => level.id === id);
